### ISSUE TITLE
make an apk from rust

### ISSUE THREAD

**Issue by ssrlive** [ssrlive/droid-rust#1]
Install rust https://rustup.rs

Install some Android targets (arm64, arm, x86_64, x86) for rust.
```bash
rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
```

Install [Android Studio](https://developer.android.com/studio)

Install Android SDK and NDK

![sdk](https://raw.githubusercontent.com/ssrlive/rust_on_android_ios/main/sdk.png)

Reboot your computer.

Quick start for setting up a new project with support for Android. For communication with the Android framework in our native Rust application we require a `NativeActivity`. `ndk-glue` will do the necessary initialization when calling `main` but requires a few adjustments:

`Cargo.toml`
```TOML
[package]
name = "myrustdemo"
version = "0.1.0"
edition = "2021"

[[example]]
name = "hello"
path = "src/hello.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
jni = "0.19.0"
libc = "0.2"
log = "0.4.14"
ndk = { version = "0.6.0", features = ["trace"] }
ndk-glue = { version = "0.6.0", features = ["logger"] }

[package.metadata.android]
# Specifies the package property of the manifest.
package = "com.foobar.hello"

# Specifies the array of targets to build for.
build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]

[package.metadata.android.sdk]
min_sdk_version = 16
target_sdk_version = 31

[package.metadata.android.application.activity]
label = "MyRustActivity"
exported = true
```

Wraps `main` function using attribute macro `ndk::glue::main`:

`src/hello.rs`
```rust
#[cfg_attr(target_os = "android", ndk_glue::main(backtrace = "on"))]
pub fn main() {
    println!("hello =========== world");
}
```

Install `cargo apk` for building, running and debugging your application:
```bash
#cargo install cargo-apk
git clone https://github.com/rust-windowing/android-ndk-rs.git ndk-rs
cargo install --path ./ndk-rs/cargo-apk
```

Set environment variables of `NDK`
```
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk/24.0.8215888
```
> In windows machine, run
> ```
> set ANDROID_NDK_ROOT=C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\24.0.8215888
> set ANDROID_SDK_ROOT=C:\Users\Administrator\AppData\Local\Android\Sdk
> ```

We can now directly execute our Hello World application on a real connected device or an emulator:
```
cargo apk run --example hello
```
